"""Seeding data and adding table object

Revision ID: 4720114980fc
Revises: 1e757b6b0216
Create Date: 2024-09-16 21:55:09.723328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4720114980fc'
down_revision: Union[str, None] = '1e757b6b0216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['band_id'], ['bands.id'], name=op.f('fk_band_venues_band_id_bands')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_band_venues_venue_id_venues')),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('bands', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('bands', 'hometown',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concerts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concerts', 'date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('concerts', 'band_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('concerts', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venues', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('venues', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('concerts', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('concerts', 'band_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('concerts', 'date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('concerts', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bands', 'hometown',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bands', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('band_venues')
    # ### end Alembic commands ###
